### ISSUE TITLE
looks like my cool .env

### ISSUE THREAD

**Issue by Aspect0002** [mxnty999/SilverBot#1]
i am pepe and i am back lol
looks like my .env uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu

**Comment by mxnty999** [comment]
where is the status kek

**Comment by Aspect0002** [comment]
ppl dont have to promote hehehe

**Comment by ilovekids2** [comment]
👁👄👁

**Comment by Aspect0002** [comment]
you have accccess 
kekw
